### ISSUE TITLE
"area" issue

### ISSUE THREAD

**Issue by matteopic** [rhyst/vscode-therion-language#11]
Syntax highlight for `area` block and its type does not work.

In the followig examples the words `area`, `blocks`, `debris` and `endarea` are ignored.
```
area blocks
  l95-794-3032
  l30-382-2956
endarea

area debris
  l95-794-3032
  l30-382-2956
endarea
```

**Comment by rhyst** [comment]
I've just pushed an update that should add highlighting for _all_ the commands mentioned in the Therion manual, so hopefully this should now work.
