### ISSUE TITLE
"Watch" function

### ISSUE THREAD

**Issue by Dehautenbas** [rhyst/vscode-therion-language#23]
Is there a way to compile by watching function only when files are saved, not when they are modified?
Because when you're working in vscode, that produce multiples compiling in few secondes

**Comment by rhyst** [comment]
It has been a while since I worked on this extension but I think that is already how it works? Do you have autosave enabled?

**Comment by Dehautenbas** [comment]
Oh yeah, that was indeed due to autosave !
It was so stupid, I hadn't thought of that.
Thank's for this and for this very useful extension !

**Comment by Dehautenbas** [comment]
@rhyst  Sorry for my another question, I'm a new user of this function.

Before and just after my problem with autosave, it seemed to me that when I runed _Watching_, , the watched file appeared on the bottom status bar of vscode. 
<img width="850" alt="Capture d’écran 2024-12-14 à 12 01 35" src="https://github.com/user-attachments/assets/a8b227ea-8312-44fc-9b7d-eecd82d7167c" />
Now I have nothing here and the _Watching_ function doesn't works.

Reinstall extension and restart computer doesn't change anything.

Do you have some idea?
Thanks !
